version: 0.2

phases:
  install:
    commands:
      - echo "[INSTALL]"
  pre_build:
    commands:
      - echo "[PREBUILD]"
      - sh scripts/set_env.sh
  build:
    commands:
      - echo "[BUILD]"
      - sh scripts/build.sh
  post_build:
    commands:
      - echo "[POST_BUILD]"

artifacts:
  files:
    - '**/*'
  name: api_server_$CODEBUILD_BUILD_NUMBER.zip
